<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_formation' => [[], ['_controller' => 'App\\Controller\\FormationController::index'], [], [['text', '/formation']], [], [], []],
    'app_formation_show' => [['id'], ['_controller' => 'App\\Controller\\FormationController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/formation']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\FormationController::home'], [], [['text', '/']], [], [], []],
    'ajouter' => [[], ['_controller' => 'App\\Controller\\FormationController::ajouter'], [], [['text', '/ajouter']], [], [], []],
    'modifier_formation' => [['id'], ['_controller' => 'App\\Controller\\FormationController::editFormation'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/modifier']], [], [], []],
    'supprimer_formation' => [['id'], ['_controller' => 'App\\Controller\\FormationController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/supprimer']], [], [], []],
    'app_participant' => [[], ['_controller' => 'App\\Controller\\ParticipantController::index'], [], [['text', '/participant']], [], [], []],
    'liste_participant' => [[], ['_controller' => 'App\\Controller\\ParticipantController::afficherList'], [], [['text', '/liseteparticipant']], [], [], []],
    'ajoute_participant' => [[], ['_controller' => 'App\\Controller\\ParticipantController::ajouterParticipant'], [], [['text', '/ajouteparticipant']], [], [], []],
    'supprimer_participant' => [['id'], ['_controller' => 'App\\Controller\\ParticipantController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/supprimerparticipant']], [], [], []],
    'modifier_participant' => [['id'], ['_controller' => 'App\\Controller\\ParticipantController::editParticipant'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/modifierparticipant']], [], [], []],
    'show_participant' => [['id'], ['_controller' => 'App\\Controller\\ParticipantController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/showparticipant']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
